version: '3.1'

services:

  mongo:
    image: mongo
    volumes:
      - ./data:/exercisedata
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: databases
      ME_CONFIG_MONGODB_URL: mongodb://root:databases@mongo:27017/
